### ISSUE TITLE
Grab coordinates from cursor position

### ISSUE THREAD

**Issue by Towandaa** [chreden/trview#1003]
Would it be possible to add a menutitem in the Contextual Menu we have to "add way point" to directly copy the coordinates of where we clicked? (and maybe one for the room number too)

When testing secrets / vehicle localisation in rando... when you have no entity nor close enough waypoint to spawn on you are forced to create a waypoint, grab coordinates and delete it , it would be cool to have a way to do it faster.

Thanks

**Comment by chreden** [comment]
I've checked and this is easy to do, so I'll add it soon. Thanks for the suggestion!

**Comment by Towandaa** [comment]
> I've checked and this is easy to do, so I'll add it soon. Thanks for the suggestion!

You are welcome! Thanks
