### ISSUE TITLE
Add an "Open route window at startup" in the settings... and populate it?

### ISSUE THREAD

**Issue by Towandaa** [chreden/trview#1004]
If i'm not mistaken  the settings are missing the possibility to open the route window at startup.

And to fully write my letter to santa , a way to say "when loading a level i want THIS file to be imported " would be a blast!

**Comment by chreden** [comment]
Route window at startup is easy, I'll add that.

Binding a route to a level is a bit more complicated, but it's a good idea. I think it would need changes like this:

- Route can be 'open' in the same way a level is
- Import renamed to Open
- Export split into Save and Save As. Save would just save the current route file where it is and Save As would let you do locations export when Rando is enabled.
- A button/checkbox in the settings for the route to bind to the current level (this would actually set a settings on the program level)
- Probably a New button to make a new route

The import/export renaming would just to be clear about the change in behaviour as import/export implies a copy.

**Comment by Towandaa** [comment]
I felt this need while placing some secrets and testing them .... 
To see secrets location you need to 
Open route window
Import
Select the file (ALWAYS location.json no matter what level) 
Ok
And now you can see ...
But when you restart or change level it goes away.

So I was like "wouldn't it be so cool having the route window opened and location.json loaded automatically???" **:D**
I wasn't thinking about binding a file to a level specifically as location.json works for everyone of them. 
Maybe you can have some different behaviour for the actual routes (not sure how that part works I never did any route) from the locations file? But might be complicated, the UI needs to follow so we don't get confuse ^^

Thanks for your rapid answer anyway ! :D

**Comment by chreden** [comment]
Yes I think I over thought it. How about:
- Add open route at startup
- When you open a level it asks you if you want to import the last thing you exported (for that level)
