### ISSUE TITLE
Save Layout?

### ISSUE THREAD

**Issue by Towandaa** [chreden/trview#1010]
It would be cool to have every window that we ask to be open at the start (including main window) at the same place as when we left them when we reopen the app. I feel docking windows kinda do that but main window is opening in "the middle ish " of the screen and... having been blessed with a big screen... i have to move the main on the right... route on the left to have them side by side. 

If its possible i don't know how :) maybe i close the app too violently ^^
No biggy if it's too much of a hassle

**Comment by chreden** [comment]
Yes, the docking windows will remember this as ImGui takes care of that. I can add it for the main window.
