### ISSUE TITLE
Show yaw angle only as positive number

### ISSUE THREAD

**Issue by TempleOfHorus** [chreden/trview#1016]
Self describing. Negative values are confusing.
![ANG1](https://user-images.githubusercontent.com/60355056/192095229-a368c91b-4a10-48d1-88ab-3a40664b0839.jpg)

**Comment by chreden** [comment]
Does this only apply to the yaw or the pitch too? I don't think it makes as much sense for pitch as looking down 10 degrees would be 350. I think the positive/negative makes more sense there.

**Comment by TempleOfHorus** [comment]
> Does this only apply to the yaw or the pitch too? I don't think it makes as much sense for pitch as looking down 10 degrees would be 350. I think the positive/negative makes more sense there.

This should be applied only to the yaw. As you wrote, for pitch it makes more sense to use positive/negative.

**Comment by chreden** [comment]
You can download the build of this from here https://github.com/chreden/trview/actions/runs/3155279759
