### ISSUE TITLE
Crash with converted TUB file

### ISSUE THREAD

**Issue by lahm86** [chreden/trview#1136]
The PHD file in the attached zip crashes trview, but not all the time. This is converted from the TUB file also attached, by reading the palette between sprite sequences and cameras instead of the usual place between light map and cinematic frames. This level is apparently part of the TRUB3DFX release (https://www.dosgamesarchive.com/file/tomb-raider-unfinished-business/trub3dfx).

[EGYPT.zip](https://github.com/chreden/trview/files/10952139/EGYPT.zip)

A possible cause of the crash is that room 9 references a sprite texture that doesn't exist. But there may be other problems in the file (this problem came to light via an issue raised for Tomb1Main - https://github.com/LostArtefacts/Tomb1Main/issues/754).

**Comment by chreden** [comment]
Yes, it's referencing sprite texture 140 in room 9. No other obvious issues with it. Will figure out what to return in this case.
