### ISSUE TITLE
Enemy type snowmobiles aren't visible in trview

### ISSUE THREAD

**Issue by aredfan** [chreden/trview#1215]
**The following levels are affected:**
- Tibetan Foothills (SKIDOO)
- The Cold War (LEVEL1)
- Fool's Gold (LEVEL2)

![Screenshot (1205)](https://github.com/chreden/trview/assets/94776985/9d518477-2834-4d40-b8f3-20e782b8bc32)

**Comment by chreden** [comment]
It's been like this forever, but I never thought to look into why. I'll see if there's something we can do about it.

**Comment by chreden** [comment]
They aren't visible because they don't exist - the game generates a skidoo when it sets up the skidoo driver. We can do the same thing though. Will look like this once it goes in

![image](https://github.com/chreden/trview/assets/4263940/4ba3eede-e540-4974-af3e-c50982827a52)

**Comment by chreden** [comment]
Will be in next version or you can take the [build of master](https://github.com/chreden/trview/actions/runs/7966325570)

**Comment by aredfan** [comment]
I tested the build myself and all black skidoos are visible now.  Looks beautiful.  Thank you for working on this 👍
