### ISSUE TITLE
Show extra camera FD details

### ISSUE THREAD

**Issue by lahm86** [chreden/trview#1280]
Would it be possible to show the broken down extra details for camera triggers in the Rooms window? Currently the raw value remains when you switch that option off. Would be useful to see the four values separately.

https://opentomb.github.io/TRosettaStone3/trosettastone.html#:~:text=Camera%20trigger%20action%20uses%20one%20extra

![image](https://github.com/user-attachments/assets/448f703a-e0ce-4fbe-a71f-0153ede7e6da)

**Comment by chreden** [comment]
Yes that makese sense, I'll add a step for that. Must have missed it when adding non-raw mode.
