### ISSUE TITLE
View Menu

### ISSUE THREAD

**Issue by jw-dev** [chreden/trview#130]
A view menu would be nice, some possible options:
- Show/hide minimap
- Show/hide tooltip on the 3d view when hovering over rooms (if user is working in one room, this may be frustrating) 
- Show/hide ui (potentially, show/hide ui elements - depending on how granular we want it)
- Some rendering options - wireframe, TRLE colors, etc?

**Comment by chreden** [comment]
This will have everything apart from the rendering options, as there aren't any options to choose yet.
When these options are added they will be added to the view menu.
