### ISSUE TITLE
Merge tr_room_sector and Sector

### ISSUE THREAD

**Issue by jw-dev** [chreden/trview#138]
For the minimap, I wrote a Sector class where each square on the map is a "Sector", and a lot of data is copied over to this class from tr_room_sector. Either these objects should be merged into one, or Sector should inherit from tr_room_sector, not sure. If merging into one object we could parse floor data as part of the level load (rather than having it be part of Map) - we're going to need that later, anyway

**Comment by chreden** [comment]
I don't think this is needed any more - the sector class has grown a bit and floordata is being parsed too outside of the map. tr_room_sector can stay as pure data.
