### ISSUE TITLE
List items on a square

### ISSUE THREAD

**Issue by makotocchi** [chreden/trview#167]
There should be an easy way of listing every pickup that is located on a square. Helps if the items are stacked. Maybe click on the square and have something tell you what's in it.

**Comment by chreden** [comment]
As suggested the idea is to be able to select a square by either clicking in the world or on the minimap. Then the triggers and items windows can have a similar function to 'Track Room' where they would track the currently selected sector.

Arrow keys to change sector selection? Could get confusing as the arrow keys also change the selection in the t/i/r windows - but only when you have them selected.
