### ISSUE TITLE
TRLE colours mode

### ISSUE THREAD

**Issue by makotocchi** [chreden/trview#49]
The program needs a way of temporarily disabling the original textures and instead texture the level using TRLE colours (blue floor, green walls, pink triggers etc). This will make it much easier to discern squares and triggers.

- There should be an option in the view menu to toggle TRLE colours
- When selected, texture rendering should be disabled and replaced with TRLE colours

Notes:
Hidden geometry should be rendered, as it would be seen if it was the TRLE editor.
Walls are not currently rendered, so they'll have to be added when they're added.

- [x] Add checkbox to view options to toggle TRLE colours mode
- [x] Override colours for level mesh somehow
- [ ] Add tests
- [x] Fix walls on portals
- [x] Fix ceilings on walls
- [x] Fix big columns
- [ ] Triangles are in the wrong direction on the floor (eg - SW -> NE instead of SE -> NW)
- [x] Remove duplicate triangles
- [x] Add grid instead of chequerboard
- [x] Ceiling triangulation in TR3+
- [x] Floor triangulation in TR3+ (diagonal half tiles)
- [x] Use TRLE mesh for collision mesh

**Comment by chreden** [comment]
Cave oddity
![image](https://user-images.githubusercontent.com/4263940/132595916-2eb432a7-b818-4625-8145-1c6d47000bac.png)

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132770807-81113a9c-73a2-430c-80df-7687271b4934.png)
Walls next to portals are visible

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132770976-f08d62ce-ef1f-4254-abd2-337a1c0b9cc4.png)
Wall with two textures

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132771076-0454bac8-7989-480f-b13a-d64daf36e9e3.png)
Tall walls that aren't supposed to be there.

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132771237-53a26099-c2c7-4db8-96a9-2f2bf29bba73.png)
I think no-space is getting rendered.

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132771293-07f1f72a-4311-4693-87cd-bfb1ffc18e9e.png)
One of the sides of the wall has a transparent texture and the other side doesn't. Causes rendering issues. Not sure what you could do about it

**Comment by makotocchi** [comment]
![image](https://user-images.githubusercontent.com/7460385/132772010-c5ff3646-b4fe-4620-a3ba-a3fc4e28f0e3.png)
Missing textures.

**Comment by chreden** [comment]
![image](https://user-images.githubusercontent.com/4263940/133910751-abb1dfb4-74ad-4bfd-b2e0-67155e518c4a.png)

North -> South or South -> North aren't making matched triangles. They need to match and then need de-duping on the triangles.

**Comment by chreden** [comment]
![image](https://user-images.githubusercontent.com/4263940/133928761-04c86180-eb65-4155-b30d-7ddb98923cfa.png)

Z-Fighting here. Caused by triangles being present in adjacent rooms. Needs cross room-deduplication which might be quite complicated.

**Comment by chreden** [comment]
![image](https://user-images.githubusercontent.com/4263940/136113362-7fc13071-5e60-41e2-ab33-d76d24ebe698.png)

TR3 triangles missing in Puna
