### ISSUE TITLE
Room geometry not showing for this level

### ISSUE THREAD

**Issue by sapper-trle** [chreden/trview#620]
Any idea what might be causing incorrect texturing in this TR4 level xmas in seville?
Which routines in code should I look at?
Level was built using Tomb Editor but fexinspect displays rooms correctly.
Note level uses an extended soundmap (v130) which your program doesn't support yet.
Also one room references non existing static which causes crash which I adjusted code for.
Level has 329 texture pages and 9679 textures.
I am using a debug version of trview.
  
![trview](https://user-images.githubusercontent.com/8148073/71795881-6a058700-309c-11ea-96b5-52e82027188f.png)

**Comment by chreden** [comment]
Hmm I'm not sure exactly. First thing I'd check is if the textures that aren't showing up are actually loaded correctly, DirectX debugging tools can show the loaded textures. I can look when I get some time.

**Comment by chreden** [comment]
With the current version it is failing to load the level at all due to the new sound details. I will figure out why this is failing, or just stop loading sound - I never use it anyway. Then I can move on to figuring out the texture issue, if it is still there.

**Comment by chreden** [comment]
I was adding values to the UV coordinates which meant it was using the wrong ones. @sapper-trle do you mind if I C&P your fix almost verbatim for v130 sound maps and put it in this PR, or would you like to do a PR from your fork into here?

**Comment by chreden** [comment]
This has caused seams to appear in regular levels, so a better fix needs to be found for this.
