### ISSUE TITLE
TIMER_FIELD trigger not recognised

### ISSUE THREAD

**Issue by chreden** [chreden/trview#632]
From Woops:
```
in highstrt.tr4 (Citadel Gate) these three triggers in room 58 are "unknown"(?) 
In fexinspect it says "TIMER_FIELD(1023)"
```

![image](https://user-images.githubusercontent.com/4263940/72759536-e1273900-3bcd-11ea-806f-6c334d09bc9d.png)

It should show TIMER_FIELD

**Comment by sapper-trle** [comment]
I think this is a bug with fexinspect. TIMER_FIELD is a TRNG trigger field which should not apply to original TR4 levels. So it really is unknown. Interesting. TIMER_FIELD isn't in original TRLE objects.h file.

**Comment by chreden** [comment]
@Trxyebeep has investigated, these really are just corrupt triggers. trview is displaying them as correctly as it can.
