### ISSUE TITLE
Show angle of camera

### ISSUE THREAD

**Issue by TempleOfHorus** [chreden/trview#633]
The camera angle would help us set angle of Lara properly to get ALTs - useful for researching.

**Comment by chreden** [comment]
This would be in orbit mode only and could be displayed near the camera coordinate display.

**Comment by TempleOfHorus** [comment]
Yes,  display it near the camera coordinates is good idea. But why it would be only in orbit mode and not for all (or at least for free mode) ? Also I was thinking we can use measure tool to show angle for ALTs - one end of measure tool would show position of Lara and second end place where she wants to look (or we can show angle from both sides).
