### ISSUE TITLE
Route window - Add setting to show position relative to the room instead of world

### ISSUE THREAD

**Issue by makotocchi** [chreden/trview#726]
![image](https://user-images.githubusercontent.com/7460385/104857858-055d4900-58fa-11eb-8477-656af0995b77.png)

Instead of showing "34436, 30976, 88451", show the room number and the node coordinates relative to it. It would be useful when using TRMOD to modify the levels since it only accepts room coordinates.

**Comment by chreden** [comment]
This can be another property in the properties list - `Room Position` or something. Room number is also easy enough to add as it is contained in the pick information.
